# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App

  target 'AppTests' do
    inherit! :search_paths
    # Pods for testing
pod 'SwiftyJSON', '~> 2.3'
pod 'Alamofire', '~> 5.2'
  end

  target 'AppUITests' do
    # Pods for testing
  end

end
